/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Test1 = {
  _id: string;
  _type: "test-1";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  heroMedia?: MediaAsset;
  blocks?: Array<
    | ({
        _key: string;
      } & Block_1)
    | ({
        _key: string;
      } & Block_2)
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MediaAsset = {
  _type: "mediaAsset";
  mediaType?: "image" | "video";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: MuxVideo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Motion_page = {
  _id: string;
  _type: "motion_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Fotografia_page = {
  _id: string;
  _type: "fotografia_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Layout_page = {
  _id: string;
  _type: "layout_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Tipografia_page = {
  _id: string;
  _type: "tipografia_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Ilustracion_page = {
  _id: string;
  _type: "ilustracion_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Iconografia_page = {
  _id: string;
  _type: "iconografia_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Patrones_page = {
  _id: string;
  _type: "patrones_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Brand_colors_page = {
  _id: string;
  _type: "brand_colors_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Trademarks_page = {
  _id: string;
  _type: "trademarks_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Recursos_page = {
  _id: string;
  _type: "recursos_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Asi_nos_vemos_page = {
  _id: string;
  _type: "asi_nos_vemos_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Asi_hablamos_page = {
  _id: string;
  _type: "asi_hablamos_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Nuestra_marca_page = {
  _id: string;
  _type: "nuestra_marca_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
};

export type Home_page = {
  _id: string;
  _type: "home_page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    media?: MediaAsset;
  };
  textSlides?: {
    textSlide1?: I18nText;
    textSlide2?: I18nText;
  };
  imageZoom?: MediaAsset;
  imagesGrid?: {
    image1?: MediaAsset;
    image2?: MediaAsset;
    image3?: MediaAsset;
    image4?: MediaAsset;
  };
  imageEye?: MediaAsset;
  bookText?: I18nText;
  words?: {
    word1?: I18nString;
    word2?: I18nString;
    word3?: I18nString;
  };
};

export type I18nString = {
  _type: "i18n.string";
  es?: string;
  ca?: string;
};

export type I18nText = {
  _type: "i18n.text";
  es?: string;
  ca?: string;
};

export type Block_2 = {
  _type: "block_2";
  media1?: MediaAsset;
  media2?: MediaAsset;
};

export type Block_1 = {
  _type: "block_1";
  media1?: MediaAsset;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type I18nNumber = {
  _type: "i18n.number";
  es?: number;
  ca?: number;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Test1
  | SanityImageAssetReference
  | MediaAsset
  | Slug
  | Motion_page
  | Fotografia_page
  | Layout_page
  | Tipografia_page
  | Ilustracion_page
  | Iconografia_page
  | Patrones_page
  | Brand_colors_page
  | Trademarks_page
  | Recursos_page
  | Asi_nos_vemos_page
  | Asi_hablamos_page
  | Nuestra_marca_page
  | Home_page
  | I18nString
  | I18nText
  | Block_2
  | Block_1
  | MuxVideoAssetReference
  | MuxVideo
  | SanityImageCrop
  | SanityImageHotspot
  | I18nNumber
  | MuxVideoAsset
  | MuxAssetData
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/pages.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "home_page" && _id == "home_page"][0]{    hero {      media {  mediaType,  image,  video {    asset->{      playbackId    }  }}    },    textSlides {      textSlide1,      textSlide2    },    imageZoom {  mediaType,  image,  video {    asset->{      playbackId    }  }},    imagesGrid {      image1 {  mediaType,  image,  video {    asset->{      playbackId    }  }},      image2 {  mediaType,  image,  video {    asset->{      playbackId    }  }},      image3 {  mediaType,  image,  video {    asset->{      playbackId    }  }},      image4 {  mediaType,  image,  video {    asset->{      playbackId    }  }}    },    imageEye {  mediaType,  image,  video {    asset->{      playbackId    }  }},    bookText,    words {      word1,      word2,      word3    }  }
export type HOME_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
  textSlides: {
    textSlide1: I18nText | null;
    textSlide2: I18nText | null;
  } | null;
  imageZoom: {
    mediaType: "image" | "video" | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    video: {
      asset: {
        playbackId: string | null;
      } | null;
    } | null;
  } | null;
  imagesGrid: {
    image1: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
    image2: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
    image3: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
    image4: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
  imageEye: {
    mediaType: "image" | "video" | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    video: {
      asset: {
        playbackId: string | null;
      } | null;
    } | null;
  } | null;
  bookText: I18nText | null;
  words: {
    word1: I18nString | null;
    word2: I18nString | null;
    word3: I18nString | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: NUESTRA_MARCA_PAGE_QUERY
// Query: *[_type == "nuestra_marca_page" && _id == "nuestra_marca_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type NUESTRA_MARCA_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: ASI_HABLAMOS_PAGE_QUERY
// Query: *[_type == "asi_hablamos_page" && _id == "asi_hablamos_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type ASI_HABLAMOS_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: ASI_NOS_VEMOS_PAGE_QUERY
// Query: *[_type == "asi_nos_vemos_page" && _id == "asi_nos_vemos_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type ASI_NOS_VEMOS_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: RECURSOS_PAGE_QUERY
// Query: *[_type == "recursos_page" && _id == "recursos_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type RECURSOS_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: TRADEMARKS_PAGE_QUERY
// Query: *[_type == "trademarks_page" && _id == "trademarks_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type TRADEMARKS_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: BRAND_COLORS_PAGE_QUERY
// Query: *[_type == "brand_colors_page" && _id == "brand_colors_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type BRAND_COLORS_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: PATRONES_PAGE_QUERY
// Query: *[_type == "patrones_page" && _id == "patrones_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type PATRONES_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: ICONOGRAFIA_PAGE_QUERY
// Query: *[_type == "iconografia_page" && _id == "iconografia_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type ICONOGRAFIA_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: ILUSTRACION_PAGE_QUERY
// Query: *[_type == "ilustracion_page" && _id == "ilustracion_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type ILUSTRACION_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: TIPOGRAFIA_PAGE_QUERY
// Query: *[_type == "tipografia_page" && _id == "tipografia_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type TIPOGRAFIA_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: LAYOUT_PAGE_QUERY
// Query: *[_type == "layout_page" && _id == "layout_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type LAYOUT_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: FOTOGRAFIA_PAGE_QUERY
// Query: *[_type == "fotografia_page" && _id == "fotografia_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type FOTOGRAFIA_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: MOTION_PAGE_QUERY
// Query: *[_type == "motion_page" && _id == "motion_page"][0]{  hero {    media {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}
export type MOTION_PAGE_QUERY_RESULT = {
  hero: {
    media: {
      mediaType: "image" | "video" | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      video: {
        asset: {
          playbackId: string | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/queries/pages.ts
// Variable: TEST_1_QUERY
// Query: *[_type == "test-1" && _id == "test-1"][0]{    title,    heroMedia {  mediaType,  image,  video {    asset->{      playbackId    }  }},    blocks []{  _key,  _type,  _type == "block_1" => {    media1 {  mediaType,  image,  video {    asset->{      playbackId    }  }}  },  _type == "block_2" => {    media1 {  mediaType,  image,  video {    asset->{      playbackId    }  }},    media2 {  mediaType,  image,  video {    asset->{      playbackId    }  }}  }}  }
export type TEST_1_QUERY_RESULT = {
  title: string | null;
  heroMedia: {
    mediaType: "image" | "video" | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    video: {
      asset: {
        playbackId: string | null;
      } | null;
    } | null;
  } | null;
  blocks: Array<
    | {
        _key: string;
        _type: "block_1";
        media1: {
          mediaType: "image" | "video" | null;
          image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          video: {
            asset: {
              playbackId: string | null;
            } | null;
          } | null;
        } | null;
      }
    | {
        _key: string;
        _type: "block_2";
        media1: {
          mediaType: "image" | "video" | null;
          image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          video: {
            asset: {
              playbackId: string | null;
            } | null;
          } | null;
        } | null;
        media2: {
          mediaType: "image" | "video" | null;
          image: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          video: {
            asset: {
              playbackId: string | null;
            } | null;
          } | null;
        } | null;
      }
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "home_page" && _id == "home_page"][0]{\n    hero {\n      media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n    },\n    textSlides {\n      textSlide1,\n      textSlide2\n    },\n    imageZoom {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n},\n    imagesGrid {\n      image1 {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n},\n      image2 {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n},\n      image3 {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n},\n      image4 {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n    },\n    imageEye {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n},\n    bookText,\n    words {\n      word1,\n      word2,\n      word3\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "nuestra_marca_page" && _id == "nuestra_marca_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': NUESTRA_MARCA_PAGE_QUERY_RESULT;
    '\n  *[_type == "asi_hablamos_page" && _id == "asi_hablamos_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': ASI_HABLAMOS_PAGE_QUERY_RESULT;
    '\n  *[_type == "asi_nos_vemos_page" && _id == "asi_nos_vemos_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': ASI_NOS_VEMOS_PAGE_QUERY_RESULT;
    '\n  *[_type == "recursos_page" && _id == "recursos_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': RECURSOS_PAGE_QUERY_RESULT;
    '\n  *[_type == "trademarks_page" && _id == "trademarks_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': TRADEMARKS_PAGE_QUERY_RESULT;
    '\n  *[_type == "brand_colors_page" && _id == "brand_colors_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': BRAND_COLORS_PAGE_QUERY_RESULT;
    '\n  *[_type == "patrones_page" && _id == "patrones_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': PATRONES_PAGE_QUERY_RESULT;
    '\n  *[_type == "iconografia_page" && _id == "iconografia_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': ICONOGRAFIA_PAGE_QUERY_RESULT;
    '\n  *[_type == "ilustracion_page" && _id == "ilustracion_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': ILUSTRACION_PAGE_QUERY_RESULT;
    '\n  *[_type == "tipografia_page" && _id == "tipografia_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': TIPOGRAFIA_PAGE_QUERY_RESULT;
    '\n  *[_type == "layout_page" && _id == "layout_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': LAYOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "fotografia_page" && _id == "fotografia_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': FOTOGRAFIA_PAGE_QUERY_RESULT;
    '\n  *[_type == "motion_page" && _id == "motion_page"][0]{\n  hero {\n    media {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n': MOTION_PAGE_QUERY_RESULT;
    '\n  *[_type == "test-1" && _id == "test-1"][0]{\n    title,\n    heroMedia {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n},\n    blocks []{\n  _key,\n  _type,\n  _type == "block_1" => {\n    media1 {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  },\n  _type == "block_2" => {\n    media1 {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n},\n    media2 {\n  mediaType,\n  image,\n  video {\n    asset->{\n      playbackId\n    }\n  }\n}\n  }\n}\n  }\n': TEST_1_QUERY_RESULT;
  }
}
